version: '3.8'
services:
  mongo:
    image: mongo:5.0.7
    environment:
      MONGO_INITDB_ROOT_USERNAME: 3ac
      MONGO_INITDB_ROOT_PASSWORD: 3ac
    ports:
      - 27017:27017
    container_name: mongo
  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes